services:
  backend:
    build: .
    container_name: netflix-and-coding-backend
    ports:
      - "8000:8000"
    command: uvicorn backend.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
